ALTER TABLE `creature` ADD COLUMN `zone` INT NOT NULL DEFAULT '0' AFTER `map`;
ALTER TABLE `creature` ADD COLUMN `area` INT NOT NULL DEFAULT '0' AFTER `zone`;
ALTER TABLE `gameobject` ADD COLUMN `zone` INT NOT NULL DEFAULT '0' AFTER `map`;
ALTER TABLE `gameobject` ADD COLUMN `area` INT NOT NULL DEFAULT '0' AFTER `zone`;
