DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_dk_killing_machine';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_sha_feedback';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_sha_astral_shift';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_warl_health_funnel';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_sha_earth_shield';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_mage_mana_shield';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_hun_tnt';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_pal_eye_for_an_eye';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_rog_stealth';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_mage_ice_barrier';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_q12847_summon_soul_moveto_bunny';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_warr_battle_trance';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_pal_aura_mastery';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_nefarian_controled_hunter';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_pri_holy_nova';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_rog_revealing_strike';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_mage_invisibility';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_rog_combat_potency';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_gen_lightning_strike';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_kiljaeden_shadow_spike';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_dru_solar_eclipse';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_dk_chill_of_the_grave';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_dk_hungering_cold';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_dk_killing_machine';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_hun_pet_damage_spells';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_dru_glyph_healing_touch';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_dru_glyph_of_starfire';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_hun_lock_and_load_proc';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_xt002_heart_overload_periodic';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_gen_eject_passenger';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_sha_focused_insight';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_pri_chakra';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_hun_trap_launcher';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_warl_bane_of_havoc_track';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_gen_vehicle_scaling';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_hun_serpent_sting';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_dk_t12_helper';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_pri_shadowflame';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_warr_t12_2p_dd';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_warr_t13_4p_dd';
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_warr_t13_2p_protection';

INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (974, 'spell_sha_earth_shield');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (1463, 'spell_mage_mana_shield');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (755, 'spell_warl_health_funnel');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (-51474, 'spell_sha_astral_shift');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (-86183, 'spell_sha_feedback');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (51123, 'spell_dk_killing_machine');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (51127, 'spell_dk_killing_machine');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (51128, 'spell_dk_killing_machine');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (3674, 'spell_hun_tnt');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (13797, 'spell_hun_tnt');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (9799, 'spell_pal_eye_for_an_eye');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (25988, 'spell_pal_eye_for_an_eye');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (1784, 'spell_rog_stealth');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (11327, 'spell_rog_stealth');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (11426, 'spell_mage_ice_barrier');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (12601, 'spell_q12847_summon_soul_moveto_bunny');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (12964, 'spell_warr_battle_trance');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (19891, 'spell_pal_aura_mastery');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (23436, 'spell_nefarian_controled_hunter');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (23455, 'spell_pri_holy_nova');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (2098, 'spell_rog_revealing_strike');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (26679, 'spell_rog_revealing_strike');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (32612, 'spell_mage_invisibility');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (35541, 'spell_rog_combat_potency');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (35550, 'spell_rog_combat_potency');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (35551, 'spell_rog_combat_potency');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (37841, 'spell_gen_lightning_strike');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (46589, 'spell_kiljaeden_shadow_spike');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (48517, 'spell_dru_solar_eclipse');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (49149, 'spell_dk_chill_of_the_grave');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (50115, 'spell_dk_chill_of_the_grave');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (49203, 'spell_dk_hungering_cold');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (16827, 'spell_hun_pet_damage_spells');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (17253, 'spell_hun_pet_damage_spells');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (49966, 'spell_hun_pet_damage_spells');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (53508, 'spell_hun_pet_damage_spells');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (83381, 'spell_hun_pet_damage_spells');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (54825, 'spell_dru_glyph_healing_touch');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (54846, 'spell_dru_glyph_of_starfire');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (56342, 'spell_hun_lock_and_load_proc');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (56343, 'spell_hun_lock_and_load_proc');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (62826, 'spell_xt002_heart_overload_periodic');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (50630, 'spell_gen_eject_passenger');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (62539, 'spell_gen_eject_passenger');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (64614, 'spell_gen_eject_passenger');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (64629, 'spell_gen_eject_passenger');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (64630, 'spell_gen_eject_passenger');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (64631, 'spell_gen_eject_passenger');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (64632, 'spell_gen_eject_passenger');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (64633, 'spell_gen_eject_passenger');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (64634, 'spell_gen_eject_passenger');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (64635, 'spell_gen_eject_passenger');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (64636, 'spell_gen_eject_passenger');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (67393, 'spell_gen_eject_passenger');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (71767, 'spell_gen_eject_passenger');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (79737, 'spell_gen_eject_passenger');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (91669, 'spell_gen_eject_passenger');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (77800, 'spell_sha_focused_insight');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (81206, 'spell_pri_chakra');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (81208, 'spell_pri_chakra');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (81209, 'spell_pri_chakra');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (82945, 'spell_hun_trap_launcher');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (82948, 'spell_hun_trap_launcher');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (65266, 'spell_gen_vehicle_scaling');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (65635, 'spell_gen_vehicle_scaling');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (65636, 'spell_gen_vehicle_scaling');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (66666, 'spell_gen_vehicle_scaling');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (66667, 'spell_gen_vehicle_scaling');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (66668, 'spell_gen_vehicle_scaling');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (87852, 'spell_gen_vehicle_scaling');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (91401, 'spell_gen_vehicle_scaling');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (91405, 'spell_gen_vehicle_scaling');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (1978, 'spell_hun_serpent_sting');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (88453, 'spell_hun_serpent_sting');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (88466, 'spell_hun_serpent_sting');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (98996, 'spell_dk_t12_helper');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (99155, 'spell_pri_shadowflame');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (99233, 'spell_warr_t12_2p_dd');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (105907, 'spell_warr_t13_4p_dd');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (105908, 'spell_warr_t13_2p_protection');